#ifndef _SMARTRF_SETTINGS_H_
#define _SMARTRF_SETTINGS_H_


//*********************************************************************************
// Generated by SmartRF Studio version 2.11.0 (build #118)
// Tested for SimpleLink SDK version: CC13x2 SDK 2.20.xx.xx
// Device: CC1352P Rev. 1.1
//
//*********************************************************************************

#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include <ti/drivers/rf/RF.h>

// CC1352P1 is set to use High PA setting for Sub-1GHz. For CC1352P2, the user
// may set this macro to 0 to disable High PA for Sub-1GHz operation
#if !(defined USE_SUB1_HIGH_PA_SETTING)
#define USE_SUB1_HIGH_PA_SETTING 1
#endif

// TI-RTOS RF Mode Object
extern RF_Mode RF_prop;


// RF Core API commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_PA_t RF_cmdPropRadioDivSetup;
extern rfc_CMD_FS_t RF_cmdFs;
extern rfc_CMD_PROP_TX_t RF_cmdPropTx;
extern rfc_CMD_PROP_RX_t RF_cmdPropRx;
extern rfc_CMD_TX_TEST_t RF_cmdTxTest;


// RF Core API Overrides
extern uint32_t pOverrides[];


#endif // _SMARTRF_SETTINGS_H_
